# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:stable

stages:
    - deploy
    - post-deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375

services:
  - docker:dind

deploy-build-image:
  stage: deploy
  script: 
   # Write our GCP service account private key into a file
   - echo "$GCLOUD_SERVICE_KEY" | base64 -d > ./gcloud-service-key.json
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest -f  pipeline-builder/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE
